### ISSUE TITLE
【依頼】freemarket_sample_68f挙動確認

### ISSUE THREAD

**Issue by ta-ka-13** [ta-ka-13/freemarket_sample_68f#46]
■ URL
IPアドレス：18.180.21.98
Github（最終課題のリポジトリ）：https://github.com/ta-ka-13/freemarket_sample_68f

■ Basic認証
ID：admin
Pass：7777

■ テスト用アカウント
◯ 購入者用
メールアドレス：o@o.com
パスワード：1234567

◯ 購入用カード情報
番号：4242424242424242
期限：10/20
セキュリティカード：123

◯ 出品者用
メールアドレス：i@i.com
パスワード：1234567

**Comment by keisukekodama** [comment]
提出ありがとうございます！
basic認証などの情報が記入されていないので
[最終課題製作物提出方法に関して](https://qiita.com/techcamp_assistant/private/38be3d5e3703e7665afd)をご一読のうえ、再度提出フォームの提出お願いします

https://docs.google.com/forms/d/e/1FAIpQLSfwbel-Pb-WLCubi00-8oV_WOhp0XamSMsd9h8UHROi9LSRcA/viewform
